### PR TITLE
Add fingerprint ID

### PR DESCRIPTION
**Pull request by marcusteixeira**
Add a support do Fingerprint ID in alertsnitch. 

Fingerprint: 
- https://github.com/prometheus/alertmanager/pull/1945
- https://stackoverflow.com/questions/51511763/alertmanager-unique-id

### CODE REVIEW

**Comment by marcusteixeira** [comment]
@eltechguru

**Comment by pcarranza** [comment]
Hi @marcusteixeira - this project is only mirrored here from the [gitlab repo](https://gitlab.com/yakshaving.art/alertsnitch/)

Would you mind sending the PR over there? (that way we don't break the push mirror)

**Comment by marcusteixeira** [comment]
> Would you mind sending the PR over there? (that way we don't break the push mirror)

Thanks for your comment. I will send the modifications.

**Comment by marcusteixeira** [comment]
> Hi @marcusteixeira - this project is only mirrored here from the [gitlab repo](https://gitlab.com/yakshaving.art/alertsnitch/)
> 
> Would you mind sending the PR over there? (that way we don't break the push mirror)

@pcarranza Ref: https://gitlab.com/yakshaving.art/alertsnitch/-/merge_requests/23

**Pull request closed without merging**
